global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets:
      - "host.docker.internal:9090"

  - job_name: "node"
    static_configs:
    - targets:
      - "host.docker.internal:9100"

  - job_name: "model_predictor-1"
    scrape_interval: 1m
    static_configs:
    - targets:
      - "host.docker.internal:5040"